OPENAI_API_KEY = "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"
HUNTER_API_KEY = "86e708052546bac3bea5176a0a9e1b2ded717ff6"
